// Generated by scripts/update-sitemap-lastmod.mjs. Do not edit by hand;
// run `npm run seo:lastmod` after committing page changes.
export const SITEMAP_LASTMOD = {
  "/": "2026-10-09",
  "/pricing": "2026-10-08",
  "/features": "2026-10-08",
  "/features/idea-capture": "2026-10-09",
  "/features/ai-script-writer": "2026-10-09",
  "/features/teleprompter-recorder": "2026-10-09",
  "/features/transcript-video-editor": "2026-10-09",
  "/features/automatic-captions": "2026-10-09",
  "/features/social-publishing": "2026-10-09",
  "/features/content-calendar": "2026-10-09",
  "/features/content-library": "2026-10-09",
  "/blog": "2026-10-09",
  "/privacy": "2026-09-07",
  "/terms": "2026-07-19",
} as const;
