/**
 * Three worked examples of the language, written in full so the model sees
 * how the pieces fit rather than what a finished overlay should look like.
 * They are validated in a test so an example can never teach a mistake.
 */

export const COUNTER_EXAMPLE = {
  version: 1,
  duration: 4.2,
  poster: 1.8,
  background: { fill: "brand.surface", cornerRadius: 0.08 },
  nodes: [
    {
      id: "label",
      type: "text",
      text: "Customers",
      font: "modern",
      weight: "semibold",
      size: 0.09,
      color: "brand.ink",
      x: 0.08,
      y: 0.18,
      width: 0.84,
    },
    {
      id: "count",
      type: "number",
      from: 1200,
      to: 2850,
      format: "grouped",
      font: "modern",
      weight: "bold",
      size: 0.34,
      color: "brand.primary",
      x: 0.08,
      y: 0.36,
      width: 0.84,
    },
    {
      id: "bar",
      type: "rect",
      fill: "brand.primary",
      anchor: "left",
      x: 0.08,
      y: 0.8,
      width: 0.84,
      height: 0.06,
      cornerRadius: 0.03,
    },
  ],
  animations: [
    { node: "*", property: "opacity", from: 0, to: 1, start: 0, end: 0.25 },
    {
      node: "count",
      property: "value",
      from: 0,
      to: 1,
      start: 0.3,
      end: 1.6,
      easing: "outCubic",
    },
    {
      node: "bar",
      property: "scaleX",
      from: 0.42,
      to: 1,
      start: 0.3,
      end: 1.6,
      easing: "outCubic",
    },
    { node: "*", property: "opacity", from: 1, to: 0, start: 3.9, end: 4.2 },
  ],
};

export const COMPARISON_EXAMPLE = {
  version: 1,
  duration: 4,
  poster: 2.4,
  background: { fill: "brand.surface", cornerRadius: 0.08 },
  nodes: [
    {
      id: "title",
      type: "text",
      text: "Revenue",
      font: "modern",
      weight: "semibold",
      size: 0.08,
      color: "brand.muted",
      uppercase: true,
      x: 0.08,
      y: 0.08,
      width: 0.84,
    },
    {
      id: "value2023",
      type: "text",
      text: "$1.2M",
      font: "modern",
      weight: "bold",
      size: 0.11,
      color: "brand.ink",
      align: "center",
      x: 0.12,
      y: 0.3,
      width: 0.3,
    },
    {
      id: "value2024",
      type: "text",
      text: "$2.9M",
      font: "modern",
      weight: "bold",
      size: 0.14,
      color: "brand.primary",
      align: "center",
      x: 0.5,
      y: 0.1,
      width: 0.3,
    },
    {
      id: "bar2023",
      type: "rect",
      fill: "brand.muted",
      anchor: "bottom",
      x: 0.18,
      y: 0.44,
      width: 0.18,
      height: 0.34,
      cornerRadius: 0.02,
    },
    {
      id: "bar2024",
      type: "rect",
      fill: "brand.primary",
      anchor: "bottom",
      x: 0.56,
      y: 0.26,
      width: 0.18,
      height: 0.52,
      cornerRadius: 0.02,
    },
    {
      id: "baseline",
      type: "line",
      x: 0.08,
      y: 0.78,
      x2: 0.92,
      y2: 0.78,
      width: 0.84,
      height: 0.01,
      stroke: "brand.muted",
      strokeWidth: 0.008,
    },
    {
      id: "label2023",
      type: "text",
      text: "2023",
      font: "modern",
      weight: "medium",
      size: 0.08,
      color: "brand.muted",
      align: "center",
      x: 0.12,
      y: 0.82,
      width: 0.3,
    },
    {
      id: "label2024",
      type: "text",
      text: "2024",
      font: "modern",
      weight: "medium",
      size: 0.08,
      color: "brand.ink",
      align: "center",
      x: 0.5,
      y: 0.82,
      width: 0.3,
    },
    {
      id: "arrow",
      type: "path",
      d: "M 0 1 L 1 0 M 0.6 0 L 1 0 L 1 0.4",
      stroke: "brand.accent",
      strokeWidth: 0.02,
      x: 0.4,
      y: 0.3,
      width: 0.12,
      height: 0.16,
    },
  ],
  animations: [
    { node: "*", property: "opacity", from: 0, to: 1, start: 0, end: 0.25 },
    {
      node: "bar2023",
      property: "scaleY",
      from: 0,
      to: 1,
      start: 0.2,
      end: 0.9,
      easing: "outCubic",
    },
    {
      node: "bar2024",
      property: "scaleY",
      from: 0,
      to: 1,
      start: 0.5,
      end: 1.4,
      easing: "outCubic",
    },
    {
      node: "arrow",
      property: "strokeEnd",
      from: 0,
      to: 1,
      start: 1.3,
      end: 1.9,
      easing: "outCubic",
    },
  ],
};

const step = (id: string, x: number, icon: string, text: string) => ({
  id,
  type: "group",
  x,
  y: 0.22,
  width: 0.24,
  height: 0.56,
  children: [
    {
      id: `${id}-icon`,
      type: "icon",
      icon,
      color: "brand.primary",
      strokeWidth: 0.02,
      x: 0.25,
      y: 0,
      width: 0.5,
      height: 0.5,
    },
    {
      id: `${id}-text`,
      type: "text",
      text,
      font: "modern",
      weight: "semibold",
      size: 0.09,
      color: "brand.ink",
      align: "center",
      x: 0,
      y: 0.66,
      width: 1,
    },
  ],
});

const arrow = (id: string, x: number) => ({
  id,
  type: "path",
  d: "M 0 0.5 L 1 0.5 M 0.7 0.2 L 1 0.5 L 0.7 0.8",
  stroke: "brand.muted",
  strokeWidth: 0.02,
  x,
  y: 0.3,
  width: 0.08,
  height: 0.14,
});

export const FLOW_EXAMPLE = {
  version: 1,
  duration: 5,
  poster: 3,
  background: { fill: "brand.surface", cornerRadius: 0.08 },
  nodes: [
    step("step1", 0.06, "user-plus", "Sign up"),
    arrow("arrow1", 0.3),
    step("step2", 0.38, "link", "Connect"),
    arrow("arrow2", 0.62),
    step("step3", 0.7, "rocket", "Publish"),
  ],
  animations: [
    {
      node: "*",
      property: "opacity",
      from: 0,
      to: 1,
      start: 0,
      end: 0.3,
      stagger: 0.35,
    },
    {
      node: "arrow1",
      property: "strokeEnd",
      from: 0,
      to: 1,
      start: 0.5,
      end: 1,
      easing: "outCubic",
    },
    {
      node: "arrow2",
      property: "strokeEnd",
      from: 0,
      to: 1,
      start: 1.2,
      end: 1.7,
      easing: "outCubic",
    },
  ],
};

export const SCENE_EXAMPLES = [
  {
    title: "A counter: a number that climbs while a bar grows under it",
    scene: COUNTER_EXAMPLE,
  },
  {
    title:
      "A two-bar comparison with values, years, a baseline and a rising arrow",
    scene: COMPARISON_EXAMPLE,
  },
  {
    title:
      "A three-step flow: icons and labels in groups, arrows drawn on between them",
    scene: FLOW_EXAMPLE,
  },
] as const;

export const SCENE_EXAMPLES_SECTION =
  "EXAMPLES OF THE LANGUAGE\n" +
  "These show how the pieces fit together. They are not what your answer should look like: design for the brief and the box you are given.\n\n" +
  SCENE_EXAMPLES.map(
    ({ title, scene }) => `${title}:\n${JSON.stringify(scene)}`,
  ).join("\n\n");
