// Generated by scripts/app-actions/generate.py. Do not edit.
export type AppActionID = "editor.clips.setSpeed" | "editor.timeline.setLocked" | "editor.captions.setVisible" | "editor.reveals.setPolicy" | "editor.sounds.addAtReveals" | "editor.transcribe" | "editor.cleanup" | "editor.trimSilences" | "editor.designOverlays" | "editor.overlays.zoom" | "editor.overlays.keyframe" | "editor.overlays.setCrop" | "editor.masks.setRegion" | "editor.masks.remove" | "editor.video.animateFraming" | "editor.audio.addAt";

export interface ClipSpeedInput {
  clipIDs: Array<string>;
  rate: number;
}

export interface TimelineLockInput {
  clipIDs: Array<string>;
  captionIDs: Array<string>;
  locked: boolean;
}

export interface CaptionVisibilityInput {
  visible: boolean;
}

export type AppActionStatus = "applied" | "unchanged" | "rejected" | "failed" | "canceled";

export interface AppActionRequest {
  protocolVersion: number;
  id: string;
  projectID: string;
  revision: number;
  action: string;
  arguments: Record<string, unknown>;
}

export interface AppActionChange {
  targetID: string;
  property: string;
  before: string;
  after: string;
}

export interface AppActionResult {
  protocolVersion: number;
  invocationID: string;
  projectID: string;
  revision: number;
  action: string;
  status: AppActionStatus;
  message: string;
  changes: Array<AppActionChange>;
  skippedIDs: Array<string>;
  persisted: boolean;
}

export type RevealPolicy = "alwaysVisible" | "untilCue" | "alwaysHidden";

export interface RevealRegionPolicy {
  regionID: string;
  policy: RevealPolicy;
}

export interface RevealPolicyInput {
  overlayID: string;
  regions: Array<RevealRegionPolicy>;
}

export interface RevealSoundsInput {
  effectID: string;
  eventIDs: Array<string>;
}

export interface ChirpyActionCall {
  action: string;
  arguments: Record<string, unknown>;
}

export interface ChirpyPlanReply {
  message: string;
  actions: Array<ChirpyActionCall>;
}

export interface TranscribeWorkflowInput {
  instruction: string;
}

export interface CleanupWorkflowInput {
  instruction: string;
}

export interface SilenceWorkflowInput {
  instruction: string;
}

export interface OverlayWorkflowInput {
  instruction: string;
}

export interface ActionRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface OverlayBoxInput {
  x: number;
  y: number;
  width: number;
  height: number;
}

export type OverlayKeyOperation = "set" | "remove" | "clear" | "move";

export interface OverlayZoomInput {
  overlayID: string;
  target: ActionRect;
  startTime: number;
  endTime: number;
  returnStart?: number;
  returnEnd?: number;
}

export interface OverlayKeyframeInput {
  overlayID: string;
  time: number;
  operation: OverlayKeyOperation;
  destination?: number;
  box?: OverlayBoxInput;
  crop?: ActionRect;
}

export interface OverlayCropInput {
  overlayIDs: Array<string>;
  crop: ActionRect;
  time?: number;
}

export interface MaskRegionInput {
  overlayID: string;
  regionID?: string;
  label: string;
  rect: ActionRect;
  red: number;
  green: number;
  blue: number;
  policy?: RevealPolicy;
  revealTime?: number;
  opacityKeys?: Array<MaskOpacityKey>;
}

export interface MaskRemoveInput {
  overlayID: string;
  regionID: string;
}

export type TimelineAnchorKind = "time" | "playhead" | "speechStart" | "phrase" | "event";

export interface TimelineAnchorInput {
  kind: TimelineAnchorKind;
  time?: number;
  phrase?: string;
  occurrence?: number;
  eventID?: string;
  offset?: number;
}

export type AnimationEase = "linear" | "smooth";

export type AnimationPivot = "frameCenter" | "face";

export interface FramingAnimationKey {
  at: TimelineAnchorInput;
  scaleMultiplier: number;
  x?: number;
  y?: number;
  rotation?: number;
  easing?: AnimationEase;
}

export interface FramingAnimationInput {
  keys: Array<FramingAnimationKey>;
  pivot?: AnimationPivot;
}

export interface MaskOpacityKey {
  at: TimelineAnchorInput;
  opacity: number;
  easing?: AnimationEase;
}

export interface SoundAtInput {
  effectID: string;
  at: Array<TimelineAnchorInput>;
}
