// Generated by scripts/app-actions/generate.py. Do not edit.
export type AppActionID = "editor.clips.setSpeed" | "editor.timeline.setLocked" | "editor.captions.setVisible" | "editor.reveals.setPolicy" | "editor.sounds.addAtReveals" | "editor.transcribe" | "editor.cleanup" | "editor.trimSilences" | "editor.designOverlays";

export interface ClipSpeedInput {
  clipIDs: Array<string>;
  rate: number;
}

export interface TimelineLockInput {
  clipIDs: Array<string>;
  captionIDs: Array<string>;
  locked: boolean;
}

export interface CaptionVisibilityInput {
  visible: boolean;
}

export type AppActionStatus = "applied" | "unchanged" | "rejected" | "failed" | "canceled";

export interface AppActionRequest {
  protocolVersion: number;
  id: string;
  projectID: string;
  revision: number;
  action: string;
  arguments: Record<string, unknown>;
}

export interface AppActionChange {
  targetID: string;
  property: string;
  before: string;
  after: string;
}

export interface AppActionResult {
  protocolVersion: number;
  invocationID: string;
  projectID: string;
  revision: number;
  action: string;
  status: AppActionStatus;
  message: string;
  changes: Array<AppActionChange>;
  skippedIDs: Array<string>;
  persisted: boolean;
}

export type RevealPolicy = "alwaysVisible" | "untilCue" | "alwaysHidden";

export interface RevealRegionPolicy {
  regionID: string;
  policy: RevealPolicy;
}

export interface RevealPolicyInput {
  overlayID: string;
  regions: Array<RevealRegionPolicy>;
}

export interface RevealSoundsInput {
  effectID: string;
  eventIDs: Array<string>;
}

export interface ChirpyActionCall {
  action: string;
  arguments: Record<string, unknown>;
}

export interface ChirpyPlanReply {
  message: string;
  actions: Array<ChirpyActionCall>;
}

export interface TranscribeWorkflowInput {
  instruction: string;
}

export interface CleanupWorkflowInput {
  instruction: string;
}

export interface SilenceWorkflowInput {
  instruction: string;
}

export interface OverlayWorkflowInput {
  instruction: string;
}
