// Builds the icon set the overlay scene format may draw from.
//
// Lucide ships as one ES module per icon with the SVG nodes inlined. This
// reads every one of them and writes two artefacts: a JSON resource the Mac
// app bundles and turns into CGPaths, and a TypeScript name list the server
// validator checks `icon` nodes against. Run after bumping lucide-react:
//
//   node scripts/scene-icons/build.mjs
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const source = join(root, "node_modules/lucide-react/dist/esm/icons");
const swiftOut = join(
  root,
  "native-macos/Sources/YapperNative/Resources/SceneIcons",
);
const tsOut = join(root, "src/lib/studio/scene");

/** The ones the designer prompt lists by name. Anything else still renders. */
const curated = [
  "arrow-right",
  "arrow-left",
  "arrow-up",
  "arrow-down",
  "arrow-up-right",
  "arrow-down-right",
  "trending-up",
  "trending-down",
  "chevron-right",
  "chevron-down",
  "move-right",
  "check",
  "check-circle",
  "x",
  "circle-x",
  "plus",
  "minus",
  "star",
  "heart",
  "thumbs-up",
  "thumbs-down",
  "flag",
  "bookmark",
  "award",
  "trophy",
  "medal",
  "target",
  "crosshair",
  "zap",
  "flame",
  "sparkles",
  "rocket",
  "lightbulb",
  "brain",
  "eye",
  "eye-off",
  "search",
  "filter",
  "settings",
  "wrench",
  "hammer",
  "tool-case",
  "cog",
  "user",
  "users",
  "user-plus",
  "user-check",
  "smile",
  "frown",
  "meh",
  "message-circle",
  "message-square",
  "mail",
  "send",
  "phone",
  "at-sign",
  "bell",
  "megaphone",
  "mic",
  "video",
  "camera",
  "image",
  "film",
  "music",
  "play",
  "pause",
  "square",
  "circle",
  "triangle",
  "hexagon",
  "layers",
  "layout-grid",
  "list",
  "list-checks",
  "clipboard",
  "clipboard-check",
  "file",
  "file-text",
  "folder",
  "book",
  "book-open",
  "notebook",
  "pen",
  "pencil",
  "edit",
  "scissors",
  "link",
  "unlink",
  "share",
  "share-2",
  "download",
  "upload",
  "cloud",
  "cloud-upload",
  "server",
  "database",
  "hard-drive",
  "cpu",
  "monitor",
  "smartphone",
  "laptop",
  "tablet",
  "tv",
  "globe",
  "map",
  "map-pin",
  "navigation",
  "compass",
  "plane",
  "car",
  "train-front",
  "ship",
  "bike",
  "home",
  "building",
  "building-2",
  "store",
  "factory",
  "landmark",
  "shopping-cart",
  "shopping-bag",
  "credit-card",
  "wallet",
  "banknote",
  "coins",
  "dollar-sign",
  "euro",
  "percent",
  "receipt",
  "calculator",
  "bar-chart-3",
  "chart-bar",
  "chart-line",
  "chart-pie",
  "pie-chart",
  "line-chart",
  "bar-chart",
  "activity",
  "gauge",
  "timer",
  "clock",
  "calendar",
  "calendar-days",
  "hourglass",
  "alarm-clock",
  "sun",
  "moon",
  "cloud-rain",
  "snowflake",
  "thermometer",
  "umbrella",
  "leaf",
  "tree-pine",
  "flower",
  "sprout",
  "apple",
  "coffee",
  "utensils",
  "pizza",
  "dumbbell",
  "bed",
  "shield",
  "shield-check",
  "lock",
  "unlock",
  "key",
  "fingerprint",
  "alert-triangle",
  "triangle-alert",
  "alert-circle",
  "circle-alert",
  "info",
  "help-circle",
  "circle-help",
  "ban",
  "refresh-cw",
  "rotate-cw",
  "repeat",
  "shuffle",
  "infinity",
  "gift",
  "package",
  "box",
  "truck",
  "handshake",
  "scale",
  "gavel",
  "briefcase",
  "graduation-cap",
  "school",
  "stethoscope",
  "pill",
  "syringe",
  "heart-pulse",
  "dna",
  "atom",
  "flask-conical",
  "microscope",
  "telescope",
  "puzzle",
  "gamepad-2",
  "headphones",
  "speaker",
  "volume-2",
  "wifi",
  "bluetooth",
  "battery",
  "battery-charging",
  "plug",
  "power",
  "signal",
  "radio",
  "podcast",
  "youtube",
  "instagram",
  "facebook",
  "twitter",
  "linkedin",
  "github",
  "twitch",
  "slack",
  "figma",
  "chrome",
  "apple",
  "code",
  "terminal",
  "braces",
  "bug",
  "git-branch",
  "workflow",
  "network",
  "route",
  "footprints",
  "milestone",
  "signpost",
  "door-open",
  "quote",
  "text",
  "type",
  "hash",
  "asterisk",
  "badge-check",
  "badge-dollar-sign",
  "badge-percent",
];

function parseIconNode(text) {
  const match = /const __iconNode = (\[[\s\S]*?\]);\n/.exec(text);
  if (!match) return null;
  // The literal is JSON apart from its unquoted attribute keys. Quoting those
  // lets JSON.parse read it, so nothing from the file is ever executed.
  const json = match[1].replace(/([{,]\s*)([A-Za-z0-9_-]+)\s*:/g, '$1"$2":');
  const nodes = JSON.parse(json);
  return nodes.map(([tag, attrs]) => {
    const { key, ...rest } = attrs;
    void key;
    return [tag, rest];
  });
}

const icons = {};
for (const file of readdirSync(source)) {
  if (!file.endsWith(".js") || file.endsWith(".map")) continue;
  const name = file.slice(0, -3);
  const nodes = parseIconNode(readFileSync(join(source, file), "utf8"));
  if (nodes && nodes.length > 0) icons[name] = nodes;
}

const names = Object.keys(icons).sort();
const missing = curated.filter((name) => !icons[name]);
const curatedKept = [...new Set(curated.filter((name) => icons[name]))];

mkdirSync(swiftOut, { recursive: true });
writeFileSync(
  join(swiftOut, "lucide-icons.json"),
  JSON.stringify({ viewBox: 24, icons }),
);
mkdirSync(tsOut, { recursive: true });
writeFileSync(
  join(tsOut, "lucide-icon-names.ts"),
  `// Generated by scripts/scene-icons/build.mjs from lucide-react. Do not edit.\n` +
    `export const LUCIDE_ICON_NAMES: ReadonlySet<string> = new Set(${JSON.stringify(names)});\n\n` +
    `/** The subset the designer prompt names. Every name in LUCIDE_ICON_NAMES renders. */\n` +
    `export const CURATED_ICON_NAMES: readonly string[] = ${JSON.stringify(curatedKept)};\n`,
);

console.log(
  `${names.length} icons, ${curatedKept.length} curated` +
    (missing.length ? `, not in this lucide: ${missing.join(", ")}` : ""),
);
