"""Generate native and web contract types from the checked-in action schema.

Run with --check in CI. The runtime validates the schema before decoding inputs;
these generated types are the ergonomic API, not a substitute for validation.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
schema = json.loads((ROOT / "protocol/app-actions.schema.json").read_text())


def check_supported(definition):
    allowed = {"type", "$ref", "enum", "const", "properties", "required", "additionalProperties",
               "items", "minItems", "maxItems", "uniqueItems", "format", "minLength", "maxLength",
               "minimum", "maximum"}
    unknown = set(definition) - allowed
    if unknown:
        sys.exit(f"Add runtime validation before using schema keywords: {sorted(unknown)}")
    if "format" in definition and definition["format"] != "uuid":
        sys.exit("Only UUID string format is supported by the native validator")
    if "$ref" in definition and definition["$ref"] not in {f"#/$defs/{n}" for n in schema["$defs"]}:
        sys.exit("Action schemas must use a local named definition")
    if isinstance(definition.get("additionalProperties"), dict) and definition["additionalProperties"]:
        sys.exit("Typed additional properties are not supported")
    for child in definition.get("properties", {}).values():
        check_supported(child)
    if "items" in definition:
        check_supported(definition["items"])


for definition in schema["$defs"].values():
    check_supported(definition)


def typename(prop, swift):
    if "$ref" in prop:
        return prop["$ref"].split("/")[-1]
    kind = prop["type"]
    if kind == "array":
        inner = typename(prop["items"], swift)
        return f"[{inner}]" if swift else f"Array<{inner}>"
    if kind == "object":
        assert prop.get("additionalProperties") == {}, "Use a named definition for structured objects"
        return "[String: ActionJSON]" if swift else "Record<string, unknown>"
    if swift and prop.get("format") == "uuid":
        return "UUID"
    return ({"string": "String", "integer": "Int", "number": "Double", "boolean": "Bool"}
            if swift else {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"})[kind]


swift = ["// Generated by scripts/app-actions/generate.py. Do not edit.", "import Foundation", "",
         "enum AppActionID: String, CaseIterable, Sendable {"]
swift += [f'    case {a["symbol"]} = "{a["id"]}"' for a in schema["x-actions"]]
swift += ["}", ""]
ts = ["// Generated by scripts/app-actions/generate.py. Do not edit.",
      "export type AppActionID = " + " | ".join(json.dumps(a["id"]) for a in schema["x-actions"]) + ";", ""]
for name, definition in schema["$defs"].items():
    if "enum" in definition:
        swift += [f"enum {name}: String, Codable, Equatable, Sendable {{"]
        swift += [f"    case {value}" for value in definition["enum"]]
        swift += ["}", ""]
        ts += [f"export type {name} = " + " | ".join(json.dumps(v) for v in definition["enum"]) + ";", ""]
        continue
    swift += [f"struct {name}: Codable, Equatable, Sendable {{"]
    ts += [f"export interface {name} {{"]
    for field, prop in definition["properties"].items():
        optional = field not in definition["required"]
        swift += [f'    let {field}: {typename(prop, True)}{"?" if optional else ""}']
        ts += [f'  {field}{"?" if optional else ""}: {typename(prop, False)};']
    swift += ["}", ""]
    ts += ["}", ""]
for action in schema["x-actions"]:
    swift += [f'extension {action["input"]}: AppActionInput {{',
              f'    static var actionID: AppActionID {{ .{action["symbol"]} }}', "}", ""]
swift += ["enum AppActionContract {", f'    static let version = {schema["x-protocolVersion"]}',
          '    static let schemaJSON = #"""', json.dumps(schema, separators=(",", ":")), '"""#', "}", ""]

outputs = {
    ROOT / "native-macos/Sources/YapperNative/Models/Actions/AppActionContract.generated.swift": "\n".join(swift),
    ROOT / "protocol/app-actions.generated.ts": "\n".join(ts),
}
for path, content in outputs.items():
    if "--check" in sys.argv:
        if not path.exists() or path.read_text() != content:
            sys.exit(f"Stale action contract: {path.relative_to(ROOT)}; run python3 scripts/app-actions/generate.py")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
